
  0%|                                                                                  | 0/521 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home2/tathagato/summarization/MACSum/experiments/test_finetune_phi.py", line 288, in <module>
    train_result = trainer.train()
  File "/home2/tathagato/miniconda3/envs/roy/lib/python3.9/site-packages/trl/trainer/sft_trainer.py", line 361, in train
    output = super().train(*args, **kwargs)
  File "/home2/tathagato/miniconda3/envs/roy/lib/python3.9/site-packages/transformers/trainer.py", line 1780, in train
    return inner_training_loop(
  File "/home2/tathagato/miniconda3/envs/roy/lib/python3.9/site-packages/transformers/trainer.py", line 2118, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/home2/tathagato/miniconda3/envs/roy/lib/python3.9/site-packages/transformers/trainer.py", line 3036, in training_step
    loss = self.compute_loss(model, inputs)
  File "/home2/tathagato/miniconda3/envs/roy/lib/python3.9/site-packages/transformers/trainer.py", line 3059, in compute_loss
    outputs = model(**inputs)
  File "/home2/tathagato/miniconda3/envs/roy/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home2/tathagato/miniconda3/envs/roy/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home2/tathagato/miniconda3/envs/roy/lib/python3.9/site-packages/torch/nn/parallel/data_parallel.py", line 185, in forward
    outputs = self.parallel_apply(replicas, inputs, module_kwargs)
  File "/home2/tathagato/miniconda3/envs/roy/lib/python3.9/site-packages/torch/nn/parallel/data_parallel.py", line 200, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home2/tathagato/miniconda3/envs/roy/lib/python3.9/site-packages/torch/nn/parallel/parallel_apply.py", line 110, in parallel_apply
    output.reraise()
  File "/home2/tathagato/miniconda3/envs/roy/lib/python3.9/site-packages/torch/_utils.py", line 694, in reraise
    raise exception
torch.cuda.OutOfMemoryError: Caught OutOfMemoryError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home2/tathagato/miniconda3/envs/roy/lib/python3.9/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in _worker
    output = module(*input, **kwargs)
  File "/home2/tathagato/miniconda3/envs/roy/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home2/tathagato/miniconda3/envs/roy/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home2/tathagato/miniconda3/envs/roy/lib/python3.9/site-packages/peft/peft_model.py", line 1129, in forward
    return self.base_model(
  File "/home2/tathagato/miniconda3/envs/roy/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home2/tathagato/miniconda3/envs/roy/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home2/tathagato/miniconda3/envs/roy/lib/python3.9/site-packages/peft/tuners/tuners_utils.py", line 161, in forward
    return self.model.forward(*args, **kwargs)
  File "/home2/tathagato/miniconda3/envs/roy/lib/python3.9/site-packages/accelerate/hooks.py", line 166, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home2/tathagato/miniconda3/envs/roy/lib/python3.9/site-packages/transformers/models/gemma/modeling_gemma.py", line 1109, in forward
    outputs = self.model(
  File "/home2/tathagato/miniconda3/envs/roy/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home2/tathagato/miniconda3/envs/roy/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home2/tathagato/miniconda3/envs/roy/lib/python3.9/site-packages/accelerate/hooks.py", line 166, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home2/tathagato/miniconda3/envs/roy/lib/python3.9/site-packages/transformers/models/gemma/modeling_gemma.py", line 916, in forward
    layer_outputs = self._gradient_checkpointing_func(
  File "/home2/tathagato/miniconda3/envs/roy/lib/python3.9/site-packages/torch/_compile.py", line 24, in inner
    return torch._dynamo.disable(fn, recursive)(*args, **kwargs)
  File "/home2/tathagato/miniconda3/envs/roy/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 328, in _fn
    return fn(*args, **kwargs)
  File "/home2/tathagato/miniconda3/envs/roy/lib/python3.9/site-packages/torch/_dynamo/external_utils.py", line 17, in inner
    return fn(*args, **kwargs)
  File "/home2/tathagato/miniconda3/envs/roy/lib/python3.9/site-packages/torch/utils/checkpoint.py", line 458, in checkpoint
    ret = function(*args, **kwargs)
  File "/home2/tathagato/miniconda3/envs/roy/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home2/tathagato/miniconda3/envs/roy/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home2/tathagato/miniconda3/envs/roy/lib/python3.9/site-packages/accelerate/hooks.py", line 166, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home2/tathagato/miniconda3/envs/roy/lib/python3.9/site-packages/transformers/models/gemma/modeling_gemma.py", line 658, in forward
    hidden_states = self.mlp(hidden_states)
  File "/home2/tathagato/miniconda3/envs/roy/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home2/tathagato/miniconda3/envs/roy/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home2/tathagato/miniconda3/envs/roy/lib/python3.9/site-packages/accelerate/hooks.py", line 166, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home2/tathagato/miniconda3/envs/roy/lib/python3.9/site-packages/transformers/models/gemma/modeling_gemma.py", line 189, in forward
    return self.down_proj(self.act_fn(self.gate_proj(x)) * self.up_proj(x))
  File "/home2/tathagato/miniconda3/envs/roy/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home2/tathagato/miniconda3/envs/roy/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home2/tathagato/miniconda3/envs/roy/lib/python3.9/site-packages/peft/tuners/lora/bnb.py", line 474, in forward
    output = lora_B(lora_A(dropout(x))) * scaling
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 128.00 MiB. GPU 0 has a total capacty of 10.75 GiB of which 36.50 MiB is free. Including non-PyTorch memory, this process has 10.71 GiB memory in use. Of the allocated memory 9.64 GiB is allocated by PyTorch, and 190.75 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF